# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_file',
            field=models.FileField(null=True, upload_to='Details/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pref_time',
            field=models.DateTimeField(null=True),
        ),
    ]
