# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 14:29
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
