# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='desc',
            field=models.CharField(max_length=150),
        ),
    ]
