# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_auto_20180502_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=25),
        ),
    ]
