# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_auto_20180425_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='downvotes',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='service_category',
            name='upvotes',
            field=models.TextField(default=0, null=True),
        ),
    ]
