# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_auto_20180303_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('price', models.TextField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hire.Services')),
            ],
        ),
        migrations.DeleteModel(
            name='abc',
        ),
    ]
