# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20180303_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serces', to='hire.Services'),
        ),
    ]
