# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0005_auto_20180303_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
