# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0006_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='aadhar',
            field=models.FileField(upload_to='Details/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
