# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0006_auto_20180303_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
