# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0007_auto_20180501_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='Address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='verify',
            name='aadhar',
            field=models.FileField(upload_to='Details/None/'),
        ),
    ]
