# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0008_auto_20180306_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='xyz',
            new_name='Page',
        ),
    ]
