# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0009_auto_20180306_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='service',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='cer', to='hire.Services'),
        ),
        migrations.AddField(
            model_name='page',
            name='service_cat',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='ser_cat', to='hire.Service_category'),
        ),
    ]
