# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0010_auto_20180306_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='service',
        ),
    ]
