# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0011_remove_page_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='service_main',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='ser_main', to='hire.Services'),
        ),
    ]
