# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0012_page_service_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='namee',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
