# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0014_service_category_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='hi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_field', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
