# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0015_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hi',
        ),
    ]
