# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0016_delete_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='downvotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service_category',
            name='upvotes',
            field=models.TextField(null=True),
        ),
    ]
